version: '2'
services:
  login:
    image: ago1024/wurmunlimited:public
    ports:
      - "3724:3724"
    volumes:
      - wu_data:/data
      - wu_servers:/servers
    command: Login
  creative:
    image: ago1024/wurmunlimited:public
    ports:
      - "3725:3724"
    volumes:
      - wu_data:/data
      - wu_servers:/servers
    command: Creative
  adventure:
    image: ago1024/wurmunlimited:public
    ports:
      - "3726:3724"
    volumes:
      - wu_data:/data
      - wu_servers:/servers
    command: Adventure
volumes:
  wu_data:
  wu_servers:
